version: 0.2
env:
  parameter-store:
   DOCKER_URL: /myapp/docker-credentials/docker_url
   DOCKERHUB_USERNAME: /myapp/docker-credentials/username
   DOCKERHUB_PASSWORD: /myapp/docker-credentials/passwd
   
phases:
  install:
    runtime-versions:
      python: 3.8
   

  pre_build:
    commands:
      - echo Installing Dependencies
      - pip install -r requirements.txt
      
  build:
    commands:
      - echo "Running Docker build script..."
      - docker build -t "$DOCKERHUB_USERNAME/sample:latest" .
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - docker push "$DOCKERHUB_USERNAME/sample:latest"
    
     
      
  post_build:
    commands:
      - echo "Build is successfull"


#artifact:
 #files:
 # appspec.yaml
 # script/* .sh





