---
version: 0.2
env:
  variables:
    DOCKER_URL: /myapp/docker-credentials/docker_url
    DOCKERHUB_USERNAME: /myapp/docker-credentials/username
    DOCKERHUB_PASSWORD: /myapp/docker-credentials/passwd
    REPO_NAME: sample
    TAG: latest
phases:
  install:
    runtime version: Python 3.8
  pre_build:
    commends:
      - echo Installing Dependencies
      - pip install
      - pip install -r requirements.txt
    build:
      - echo "Running Docker build script...
      - cd simple_py_app/
      - docker build -t $DOCKERHUB_USERNAME/$REPO_NAME:$TAG .
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME"
        --password-stdin
      - docker push $DOCKERHUB_USERNAME/$REPO_NAME:$TAG
      - docker tag $DOCKERHUB_USERNAME/$REPO_NAME:$TAG
        $DOCKERHUB_USERNAME/$REPO_NAME:latest
      - docker push $DOCKERHUB_USERNAME/$REPO_NAME:latest
    post_build:
      commends: echo "Build is successfull"


#artifact:
 #files:
 # appspec.yaml
 # script/* .sh





