version: 0.2

#env variables for docker
env:
  variables:
   DOCKER_URL: "/myapp/docker-credentials/docker_url"
   DOCKERHUB_USERNAME: "/myapp/docker-credentials/username" #store in secrete in csp
   DOCKERHUB_PASSWORD: "/myapp/docker-credentials/passwd"  #store in secrete in csp
   REPO_NAME: "sample"
   TAG: "latest"

phases:
  install:
   runtime version:
    python 3.8
  pre_build:
   commends:
    - echo Installing Dependencies
    - pip install 
    - pip install -r requirements.txt
    - echo Installing Docker..
    #- apt get update -y
    #- apt get install -y docker.io
   
  build:
   - echo "Running Docker build script...
   - cd simple_py_app/
   - docker build -t $DOCKERHUB_USERNAME/$REPO_NAME:$TAG .
   - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
   - docker push $DOCKERHUB_USERNAME/$REPO_NAME:$TAG
   - docker tag $DOCKERHUB_USERNAME/$REPO_NAME:$TAG $DOCKERHUB_USERNAME/$REPO_NAME:latest
   - docker push $DOCKERHUB_USERNAME/$REPO_NAME:latest
  
  post_build:
    commends:
     echo "Build is successfull"


#artifact:
 #files:
 # appspec.yaml
 # script/* .sh





